### PR TITLE
Documentation updated to make it work

### PR DESCRIPTION
**Pull request by singh1114**
Install.sh changed and now working on 16.04

### CODE REVIEW

**Comment by singh1114** [comment]
Please accept the PR.

**Comment by amarjeetkapoor1** [comment]
Still not working on Ubuntu 16

**Comment by singh1114** [comment]
Test it now.

**Comment by amarjeetkapoor1** [comment]
@singh1114 project is working but you need to resend pull request as there are a lot of unnecessary changes and files e.g. the Your image and many others files

**Comment by singh1114** [comment]
Ok.

**Comment by singh1114** [comment]
Done.

**Comment by mandeeps708** [comment]
@amarjeetkapoor1 ping.

**Pull request closed without merging**
