### PR TITLE
Certificate Without Image

### PR DESCRIPTION
**Pull request by amisha2016**
With this PR we will be able to create certificate for both manual as well as CSV section.

### CODE REVIEW

**Review by mandeeps708 — CHANGES_REQUESTED** [review]
Why are there still lot of unnecessary comments?
200+ lines of code are comments.

**Review by vigasdeep — CHANGES_REQUESTED** [review]
I agree with Mandeep. We need to know whats going on! Add comments to code to make to explainable to others.

And, commit often. We do not want 1 single commit for 200 lines. But prefer small commits like less than 50 lines of code change in a commit.

**Comment by amisha2016** [comment]
@vigasdeep You mean to say I should commit for 50 lines of code and so on and then send single PR.

**Comment by vigasdeep** [comment]
No, I meant, Small commits. You can send multiple commits in a PR.

Small commits help others understand whats going on in smaller changes
otherwise one do not get general idea by reading 200-300 LOC.

On 09-Oct-2017 12:07 AM, "Amisha Budhiraja" <notifications@github.com>
wrote:

@vigasdeep <https://github.com/vigasdeep> You mean to say I should commit
for 50 lines of code and so on and then send single PR.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/GreatDevelopers/Certificate/pull/34#issuecomment-335028385>,
or mute the thread

**Pull request closed without merging**
